version: "3.2"

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay
    driver_opts:
      encrypted: 'yes'

secrets:
  atsea-db-password:
    external: true
  atsea-payment-token:
    external: true

services:
  database:
    image: dockersamples/atsea_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    networks:
    - back-tier
    secrets:
    - source: atsea-db-password
      target: postgres_password

  appserver:
    image: dockersamples/atsea_app
    networks:
    - front-tier
    - back-tier
    - payment
    ports:
    - 8000:8080
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
    - source: atsea-db-password
      target: postgres_password

  payment_gateway:
    image: dockersamples/atseasampleshopapp_payment_gateway
    secrets:
      - source: atsea-payment-token
        target: payment_token
    networks:
    - payment
    deploy:
      update_config:
        failure_action: rollback

